exec-once = hypridle & mako & waybar & fcitx5
exec-once = swaybg -i ~/.config/omarchy/current/background -m fill
# exec-once = systemctl --user start hyprpolkitagent # TODO user service
exec-once = wl-clip-persist --clipboard regular & clipse -listen
